resolver: lts-14.11

# paths to local packages
packages:
  - hercules-ci-api
  - hercules-ci-agent
  - tests/agent-test
extra-deps:
  - hnix-store-core-0.1.0.0@sha256:719a261870367b3ce2e2e8d11502e7170faa664109a14486b95b555bc3672807
  - nix-derivation-1.0.2@sha256:dc1f13f89d37d4dcc7a46dbac7f6b4e8cd2877f4af99e35b9cb8255d08179bd4
  - git: https://github.com/cachix/cachix
    commit: 275f732676c06aa23ae6c93049c5e54cb12ce30c
    subdirs:
      - cachix
      - cachix-api
  - git: https://github.com/hercules-ci/inline-c
    commit: 18cdcb008d070931748de1b81d7b84eb8a492a8c
    subdirs:
      - inline-c
      - inline-c-cpp

install-ghc: false  # we're using nixpkgs' ghc
system-ghc: true    # nixpkgs ghc is perceived as 'system ghc'

nix:
  packages: []      # use shell instead
  shell-file: ./nix/stack-shell.nix
  pure: false
