resolver: ghc-9.4.7

packages:
  - ./cabal-pkg-config-version-hook
  - ./hercules-ci-agent
  - ./hercules-ci-api-agent
  - ./hercules-ci-api-core
  - ./hercules-ci-api
  - ./hercules-ci-cli
  - ./hercules-ci-cnix-expr
  - ./tests/agent-test
  - ./hercules-ci-cnix-store

  # incorporate into "local" build so the tooling doesn't get confused by the
  # local -> snapshot -> local dependency, such as agent -> cachix -> cnix-store
  - ./dev/vendor/cachix/cachix
  - ./dev/vendor/cachix/cachix-api

system-ghc: true

flags:
  hercules-ci-cnix-store:
    ide: true
  hercules-ci-cnix-expr:
    ide: true
  hercules-ci-agent:
    ide: true

nix:
  enable: false
  packages: []
  shell-file: ./shell.nix
