= `hci secret add`

`hci secret add SECRET_NAME [OPTIONS]`

Insert a secret into the local `secrets.json` dotfile, for use with xref:effect/run.adoc[].

Based on the current repository branch upstream owner, the appropriate local
`secrets.json` is selected.

If a secret with the same name already exists, it will not be overwritten and the
command will return an exit status of 1.

== Parameters

[[param-SECRET_NAME]]
=== SECRET_NAME

The name of the secret that will be added. These are namespaced per account.

include::hci:partial$create-secret-options.adoc[]

[[option-project]]
=== `--project FORGE/OWNER/REPO`

Optional project path, e.g. `github/my-org/my-project`.

[[implicit-inputs]]
== Implicit inputs

This command uses `git` metadata from the working directory, unless <<option-project>> is specified.

The `secrets.json` path is xref:environment.adoc#HERCULES_CI_SECRETS_JSON[`HERCULES_CI_SECRETS_JSON`] or it is determined xref:environment.adoc#secrets.json[automatically].

== See also

For a variation of this command that writes to stdout, see xref:secret/echo.adoc[].
