= Configuration file

When deploying with NixOS, NixOps or nix-darwin you should use the module
documentation instead, or skip ahead to read about less frequently used options
to use with `extraOptions`.

The configuration format for the agent is https://github.com/toml-lang/toml#toml[TOML] markup.
Its location can be specified by invoking `hercules-ci-agent --config agent.toml`. Alternatively, the NixOS and nix-darwin module can generate this file for you. See also xref:hercules-ci:ROOT:getting-started/index.adoc#deploy-agent[the setup guide].

A basic `agent.toml` looks as follows:

[source,toml]
----
include::ROOT:partial$agent-small-example.toml[]
----

NOTE: If you are deploying an agent, the xref:hercules-ci:ROOT:getting-started/index.adoc[guide] is a better starting point.

[[apiBaseUrl]]
== apiBaseUrl

Optional. Defaults to `https://hercules-ci.com[https://hercules-ci.com]`.

API base URL that the agent will connect to.

When using Hercules CI Enterprise, set this to the URL where your Hercules CI
server is reachable.

[[baseDirectory]]
== baseDirectory

Required.

Directory with all the agent state: secrets, work, etc.

[[binaryCachesPath]]
== binaryCachesPath

Optional. Defaults to `<<staticSecretsDirectory,_staticSecretsDirectory_>>/binary-caches.json` if that file exists. With the NixOS module this defaults to `/var/lib/hercules-ci-agent/secrets/binary-caches.json`.

Path to a JSON file containing binary cache secret keys.

The format is described in xref:binary-caches-json.adoc[binary-caches.json].

[[clusterJoinTokenPath]]
== clusterJoinTokenPath

Optional. Defaults to `<<staticSecretsDirectory,_staticSecretsDirectory_>>/cluster-join-token.key`.

Path to a secret token retrieved when creating a new agent via
https://hercules-ci.com/dashboard.

This token is used for authentication with `<<apiBaseUrl,_apiBaseUrl_>>`.

[[concurrentTasks]]
== concurrentTasks

Optional. Defaults to `"auto"`. Must be an integer or `"auto"`.

Number of tasks to perform simultaneously.

A task is a single derivation build, an evaluation or an effect run.
At minimum, you need `2` concurrent tasks for <literal>x86_64-linux</literal>
in your cluster, to allow for import from derivation.

When the value is `"auto"`, the number becomes the number of CPU cores, but with
a lower bound of `2` in order to avoid deadlock during import from derivation.

The optimal value depends on the resource consumption characteristics of your workload,
including memory usage and in-task parallelism. This is typically determined empirically.

NOTE: When scaling, it is generally better to have a double-size machine than two machines,
because each split of resources causes inefficiencies; particularly with regards
to build latency because of extra downloads.

[[labels]]
== labels

Optional. A key-value map of user data.

This data will be available to organization members in the dashboard and API.

The values can be of any TOML type that corresponds to a JSON type, but arrays
can not contain tables/objects due to limitations of the TOML library. Values
involving arrays of non-primitive types may not be representable currently.

[[logLevel]]
== logLevel

Optional. Defaults to `InfoS`. More verbose: `DebugS`, less verbose: `WarningS`, `ErrorS`.

[[secretsJsonPath]]
== secretsJsonPath

Optional. Defaults to `<<staticSecretsDirectory,_staticSecretsDirectory_>>/secrets.json`.

[[staticSecretsDirectory]]
== staticSecretsDirectory

Optional. Defaults to `<<baseDirectory,_baseDirectory_>>/secrets`.

This is the default directory to look for statically configured secrets like
<<clusterJoinTokenPath>>, <<binaryCachesPath>>, <<secretsJsonPath>>.

[[workDirectory]]
== workDirectory

Optional. Defaults to `<<baseDirectory,_baseDirectory_>>/work`.

The directory in which temporary subdirectories are created for task state.
This includes sources for Nix evaluation.
