[[option-json]]
=== `--json OBJECT_PATH JSON`

WARNING: The value will be exposed in the process list for the command's short duration. Use `--json-env` or `--json-file` on systems that log process information and on multi-user systems.

Parse the `JSON` argument as JSON and add it at the specified `OBJECT_PATH`.
For example, the options

```shell
--json tls.versions '["1.3"]' --json . '{"trustOnFirstUse": false}'
```

will add a secret with the data object:

```json
{
  "tls": {
    "versions": [
      "1.3"
    ]
  },
  "trustOnFirstUse": false
}
```

[[option-json-env]]
=== `--json-env OBJECT_PATH ENV_NAME`

Parse the environment variable `ENV_NAME` as JSON and add it at the specified `OBJECT_PATH`.

[[option-json-file]]
=== `--json-file OBJECT_PATH FILE`

Parse the file content at `FILE` as JSON and add it at the specified `OBJECT_PATH`.

[[option-string]]
=== `--string OBJECT_PATH STRING`

WARNING: The value will be exposed in the process list for the command's short duration. Use `--string-env` or `--string-file` on systems that log process information and on multi-user systems.

Use `STRING` as a JSON string value and add it at the specified `OBJECT_PATH`.
For example, the options

```shell
--string host db.example.com --string parameters.compatibility classic
```

will add a secret with the data object:

```json
{
  "parameters": {
    "compatibility": "classic"
  },
  "host": "db.example.com"
}
```

[[option-string-env]]
=== `--string-env OBJECT_PATH ENV_NAME`

Use the value of environment variable `ENV_NAME` as a JSON string value and add it at the specified `OBJECT_PATH`.

[[option-string-file]]
=== `--string-file OBJECT_PATH FILE`

Read the file content at `FILE`, use it as JSON string and add it at the specified `OBJECT_PATH`.
