= `hci effect eval`

`hci effect eval [OPTIONS] ATTRIBUTE`

Evaluate an effect and print its derivation path.

This command evaluates the specified effect attribute without running it, printing the resulting derivation path to stdout. It is useful for inspecting effects, scripting, or passing the derivation to other tools.

This command pulls context from the repository and (by default) the Hercules CI API. See <<implicit-inputs>>.

== Parameters

[[param-ATTRIBUTE]]
=== ATTRIBUTE

The attribute path that leads to the effect. Tab completion is sensitive to `--pretend-branch` and such, so you want to specify that first.

[[option-no-token]]
=== `--no-token`

Don't get an API token. Allows use in an untrusted environment or unconfigured repo, but requires `--project` to be specified.

This does not inhibit use of a token provided via the xref:environment.adoc#HERCULES_CI_API_TOKEN[`HERCULES_CI_API_TOKEN`] variable.

[[option-pretend-branch]]
=== `--pretend-branch BRANCH`

Pretend we're on another git branch. This sets parameters like xref:hercules-ci-agent:ROOT:evaluation.adoc#params-herculesCI-commit[`ref` and `branch`] and `src.ref` to match `BRANCH` value.

[[option-pretend-ref]]
=== `--pretend-ref REF`

Pretend we're on another git ref. This sets parameters like xref:hercules-ci-agent:ROOT:evaluation.adoc#params-herculesCI-commit[`ref` and `branch`] and `src.ref` to match `REF` value.

[[option-pretend-tag]]
=== `--pretend-tag TAG`

Pretend we're on another git tag. This sets parameters like xref:hercules-ci-agent:ROOT:evaluation.adoc#params-herculesCI-commit[`ref` and `tag`] and `src.ref` to match `TAG` value.

[[option-project]]
=== `--project PROJECT`

Project path, e.g. `github/my-org/my-project`. Default: auto-detected.

[[implicit-inputs]]
== Implicit inputs

This command uses `git` metadata from the working directory, unless <<option-pretend-ref>> (or similar) and <<option-project>> are specified.

Information such as the project id are looked up through the Hercules CI API.

include::hci:partial$implicit-api.adoc[]
