= `hci effect run`

`hci effect run [OPTIONS] ATTRIBUTE`

Run an effect locally.

== Parameters

[[param-ATTRIBUTE]]
=== ATTRIBUTE

The attribute path that leads to the effect. Tab completion is sensitive to `--as-branch` and such, so you want to specify that first.

[[option-as-branch]]
=== `--as-branch BRANCH`

Pretend we're on another git branch. This sets the `src.ref` attribute appropriately.

[[option-as-ref]]
=== `--as-ref BRANCH`

Pretend we're on another git ref. This sets the `src.ref` attribute appropriately.

[[option-no-token]]
=== `--no-token`

Don't get an API token. Disallows access to state files, but can run in untrusted environment or unconfigured repo.

This does not inhibit use of a token provided via the xref:environment.adoc#HERCULES_CI_API_TOKEN[`HERCULES_CI_API_TOKEN`] variable.

[[option-project]]
=== `--project PROJECT`

Project path, e.g. `github/my-org/my-project`. Default: auto-detected.

[[implicit-inputs]]
== Implicit inputs

This command uses `git` metadata from the working directory, unless <<option-as-ref>> (or similar) and <<option-project>> are specified.

Values for secrets are looked up in a xref:environment.adoc#secrets.json[local `secrets.json`] or from xref:environment.adoc#HERCULES_CI_SECRETS_JSON[`HERCULES_CI_SECRETS_JSON`].

include::hci:partial$implicit-api.adoc[]
